spring:
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.java2.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.java2.mapper: debug
server:
  port: 8005

